### PR TITLE
add custom output to RunWithTesting

### PR DESCRIPTION
**Pull request by Alexey19**
This function allow to customize output. I used it to divide log output across test and change test summary.

### CODE REVIEW

**Comment by luza** [comment]
Thanks, looks as a good addition.

Btw, can your solution for tests output and summary be useful as a part of Gonkey?

**Comment by Alexey19** [comment]
> 
> 
> Thanks, looks as a good addition.
> 
> Btw, can your solution for tests output and summary be useful as a part of Gonkey?
I'm not sure. My current version of output looks like:
```
type MyOutput struct {
	output.OutputInterface

	coloredOutput output.OutputInterface
	testing *testing.T
}

func NewOutput(t *testing.T) *MyOutput {
	return &MyOutput{
		coloredOutput: console_colored.NewOutput(false),
		testing: t,
	}
}

func (o *MyOutput) Process(t models.TestInterface, result *models.Result) error {
	var err error
	if !result.Passed() {
		err = o.coloredOutput.Process(t, result)
		o.testing.Errorf("Test '%s' fails!", t.GetName())
	} else {
		fmt.Println("")
	}

	fmt.Printf("------ END of %s --------------------\n\n", t.GetName())
	return err
}
```

**Comment by What-If-I** [comment]
Hi, thanks for your pull request! That's indeed a good addition, however I'm not sure that we should increase API surface and add one more way to run Gonkey for the sake of just changing the output. Maybe we can just add one more field to `RunWithTestingParams` called something like `OutputFunc` and use default output function if it was not passed?

**Comment by Alexey19** [comment]
> Maybe we can just add one more field to `RunWithTestingParams` called something like `OutputFunc` and use default output function if it was not passed?
ok

**Review by What-If-I — APPROVED** [review]

**Pull request merged**
