### PR TITLE
Add possibility to not follow redirects

### PR DESCRIPTION
**Pull request by JustSkiv**
Some requests make redirect as result and sometimes we need just
check if url is valid, but don't have to follow it

### CODE REVIEW

**Comment by JustSkiv** [comment]
@luza @What-If-I can you take a look, please?

**Comment by luza** [comment]
IMHO, not following redirects should be taken as the default behaviour, and an option for changing this is not necessary.

The reason of writing a test is to ensure the server responds exactly as you expect. If you expect that server will redirect you, then write a test with expectation of 3XX code. If you in opposite expect server won't redirect you, then the fact of redirecting must fail the test.

**Comment by JustSkiv** [comment]
> IMHO, not following redirects should be taken as the default behaviour, and an option for changing this is not necessary.

Ok, I agree with you. Also we keep code simple in this case.

**Comment by JustSkiv** [comment]
@luza done

**Comment by JustSkiv** [comment]
@luza so, can we merge it?

**Comment by luza** [comment]
Thanks for the contribution!

**Pull request merged**
